server.port=8094

# Database Configuration (Development)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce-website
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=create-drop

# Logging (Development)
logging.level.root=INFO
logging.level.com.ecommerce.ecommercewebsite=DEBUG
logging.level.org.springframework.web=DEBUG
