server.port=8092

# Database Configuration (Development)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/payment-service
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=create-drop

# Logging (Development)
logging.level.root=INFO
logging.level.com.payment.paymentservice=DEBUG
logging.level.org.springframework.web=DEBUG
