package com.devops.bootstrap.generator;

import java.io.IOException;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

import org.apache.velocity.VelocityContext;
import org.apache.velocity.app.VelocityEngine;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.devops.bootstrap.platform.ServiceModuleConfiguration;

/**
 * TemplateEngine uses Apache Velocity to process boilerplate templates
 * with context variables from ServiceModuleConfiguration.
 * 
 * Generates production-ready source files:
 * - Spring Boot Application class
 * - REST Controllers with endpoints
 * - Service/Business logic classes
 * - Entity/JPA models
 * - DTOs for API contracts
 * - Configuration files (pom.xml, application.properties)
 */
public class TemplateEngine {
    
    private static final Logger logger = LoggerFactory.getLogger(TemplateEngine.class);
    
    private final VelocityEngine velocityEngine;
    
    public TemplateEngine() {
        this.velocityEngine = initializeVelocityEngine();
    }
    
    /**
     * Initializes and configures Apache Velocity
     */
    private VelocityEngine initializeVelocityEngine() {
        VelocityEngine ve = new VelocityEngine();
        Properties props = new Properties();
        
        // Configure Velocity to load resources from classpath 
        props.setProperty("resource.loaders", "classpath");
        props.setProperty("resource.loader.classpath.class", 
            "org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader");
        props.setProperty("input.encoding", "UTF-8");
        props.setProperty("output.encoding", "UTF-8");
        
        // Enable strict mode
        props.setProperty("runtime.strict_mode.enable", "true");
        props.setProperty("runtime.references.strict", "true");
        
        ve.init(props);
        logger.info("✓ Velocity Engine initialized");
        return ve;
    }
    
    /**
     * Processes a template with the given configuration context
     * 
     * @param templateContent the template content (inline)
     * @param config the service configuration
     * @return processed output
     */
    public String processTemplate(String templateContent, ServiceModuleConfiguration config) {
        VelocityContext context = createVelocityContext(config);
        StringWriter writer = new StringWriter();
        
        try {
            velocityEngine.evaluate(context, writer, "template", templateContent);
            return writer.toString();
        } catch (NullPointerException e) {
            logger.error("Error processing template", e);
            throw new TemplateProcessingException("Failed to process template", e);
        }
    }
    
    /**
     * Creates a Velocity context with all necessary variables
     */
    private VelocityContext createVelocityContext(ServiceModuleConfiguration config) {
        VelocityContext context = new VelocityContext();
        
        // Core configuration
        context.put("config", config);
        context.put("serviceName", config.getRequest().getServiceName());
        context.put("serviceName_pascal", config.getServiceNamePascalCase());
        context.put("serviceName_camel", config.getServiceNameCamelCase());
        context.put("package", config.getFullPackage());
        context.put("packagePath", config.getFullPackagePath());
        context.put("port", config.getRequest().getPort());
        context.put("database", config.getRequest().getDatabaseType());
        
        // Class names
        context.put("applicationClass", config.getApplicationClassName());
        context.put("serviceClass", config.getServiceClassName());
        context.put("controllerClass", config.getControllerClassName());
        context.put("repositoryClass", config.getRepositoryClassName());
        context.put("entityClass", config.getEntityClassName());
        context.put("dtoClass", config.getDtoClassName());
        
        // Maven coordinates
        context.put("mavenGroupId", config.getMavenGroupId());
        context.put("mavenArtifactId", config.getMavenArtifactId());
        context.put("mavenVersion", "1.0.0");
        
        // Docker and deployment
        context.put("dockerImage", config.getDockerImageName());
        context.put("k8sDeploymentName", config.getK8sDeploymentName());
        
        String imageVer = config.getRequest().getBaseImageVersion();
        context.put("baseImageVersion", imageVer != null ? imageVer : "17");
        
        // Metadata
        context.put("timestamp", config.getTimestamp());
        String desc = config.getRequest().getDescription();
        context.put("description", desc != null ? desc : "Microservice generated by Bootstrap Platform");
        
        // Escape helper for Spring Boot placeholders
        context.put("d", "$");
        
        return context;
    }
    
    /**
     * Generates and writes a file from a template
     */
    public void generateFile(String templateContent, String targetPath, 
                             ServiceModuleConfiguration config) throws IOException {
        String processedContent = processTemplate(templateContent, config);
        
        Path path = Paths.get(targetPath);
        Files.createDirectories(path.getParent());
        Files.write(path, processedContent.getBytes(StandardCharsets.UTF_8));
        
        logger.info("✓ Generated: {}", targetPath);
    }
    
    /**
     * Custom exception for template processing errors
     */
    public static class TemplateProcessingException extends RuntimeException {
        public TemplateProcessingException(String message, Throwable cause) {
            super(message, cause);
        }
    }
}
